// ข้อมูลสาธิต — ยกมาจาก repo Kotlin เดิม (HealthPulseDataSource.kt)
// ของจริงให้แทนที่ด้วย API ฝั่งหลังบ้าน

export const profiles = [
  {
    id: 'p1',
    name: 'หมอแพรว',
    nameEn: 'Praew',
    age: 27,
    job: 'แพทย์ประจำบ้าน',
    jobEn: 'Medical resident',
    area: 'สุขุมวิท, กรุงเทพฯ',
    areaEn: 'Sukhumvit, Bangkok',
    km: 2.4,
    tier: 'platinum',
    testedOn: '15 ส.ค. 2569',
    testedOnEn: '15 Aug 2026',
    clinic: 'รพ.บำรุงราษฎร์ อินเตอร์เนชั่นแนล',
    clinicEn: 'Bumrungrad International',
    panel: 'PCR Multiplex 28 เชื้อ + วัคซีน HPV 9 สายพันธุ์ครบโดส',
    panelEn: '28-target PCR Multiplex + full HPV 9-valent course',
    bio: 'เชื่อในความสัมพันธ์ที่ดูแลสุขภาพกันและกัน ชอบวิ่งมาราธอนกับกาแฟ specialty',
    bioEn: 'I believe in relationships where both people look after each other. Marathons and specialty coffee.',
    tags: ['สุขภาพ', 'วิ่ง', 'กาแฟ', 'ดนตรีคลาสสิก'],
    tagsEn: ['Healthcare', 'Running', 'Coffee', 'Classical'],
    accent: '#BE185D',
  },
  {
    id: 'p2',
    name: 'กานต์',
    nameEn: 'Karn',
    age: 29,
    job: 'Software Architect',
    jobEn: 'Software architect',
    area: 'สาทร, กรุงเทพฯ',
    areaEn: 'Sathorn, Bangkok',
    km: 4.1,
    tier: 'gold',
    testedOn: '1 ส.ค. 2569',
    testedOnEn: '1 Aug 2026',
    clinic: 'BDMS Wellness Clinic',
    clinicEn: 'BDMS Wellness Clinic',
    panel: 'Comprehensive STI Multiplex 28 รายการ',
    panelEn: 'Comprehensive STI Multiplex, 28 targets',
    bio: 'สาย cloud กับ privacy engineering สนใจ HealthTech และความสัมพันธ์ที่ตรงไปตรงมา',
    bioEn: 'Cloud and privacy engineering. Into health tech and being straightforward with people.',
    tags: ['เทคโนโลยี', 'บอร์ดเกม', 'ไซไฟ', 'เทนนิส'],
    tagsEn: ['Tech', 'Board games', 'Sci-fi', 'Tennis'],
    accent: '#0369A1',
  },
  {
    id: 'p3',
    name: 'มายด์',
    nameEn: 'Mind',
    age: 25,
    job: 'Digital Marketing Strategist',
    jobEn: 'Digital marketing strategist',
    area: 'อารีย์, กรุงเทพฯ',
    areaEn: 'Ari, Bangkok',
    km: 5.8,
    tier: 'silver',
    testedOn: '20 ก.ค. 2569',
    testedOnEn: '20 Jul 2026',
    clinic: 'Pulse Clinic Siam',
    clinicEn: 'Pulse Clinic Siam',
    panel: 'CDC Routine Screening 14 รายการ',
    panelEn: 'CDC routine screening, 14 targets',
    bio: 'คาเฟ่ กล้องฟิล์ม อินดี้ป็อป มองหาคนที่ดูแลตัวเองสม่ำเสมอ',
    bioEn: 'Cafes, film cameras, indie pop. Looking for someone who takes care of themselves.',
    tags: ['ถ่ายรูป', 'คาเฟ่', 'อินดี้', 'พิลาทิส'],
    tagsEn: ['Photography', 'Cafes', 'Indie', 'Pilates'],
    accent: '#0D9488',
  },
  {
    id: 'p4',
    name: 'วิน',
    nameEn: 'Win',
    age: 31,
    job: 'Private Equity Analyst',
    jobEn: 'Private equity analyst',
    area: 'สีลม, กรุงเทพฯ',
    areaEn: 'Silom, Bangkok',
    km: 3.2,
    tier: 'silver',
    testedOn: '25 มิ.ย. 2569',
    testedOnEn: '25 Jun 2026',
    clinic: 'รพ.กรุงเทพ',
    clinicEn: 'Bangkok Hospital',
    panel: 'CDC Routine Screening 14 รายการ',
    panelEn: 'CDC routine screening, 14 targets',
    bio: 'ทำงานสายการเงินแต่ให้เวลากับชีวิตนอกงาน ตรวจสุขภาพตามรอบทุก 3-6 เดือน',
    bioEn: 'Finance by day, but I protect my time outside it. I screen every 3–6 months.',
    tags: ['การเงิน', 'ไวน์', 'กอล์ฟ', 'เศรษฐศาสตร์'],
    tagsEn: ['Finance', 'Wine', 'Golf', 'Economics'],
    accent: '#4F46E5',
  },
  {
    id: 'p5',
    name: 'บอส',
    nameEn: 'Boss',
    age: 28,
    job: 'Creative Director',
    jobEn: 'Creative director',
    area: 'ทองหล่อ, กรุงเทพฯ',
    areaEn: 'Thonglor, Bangkok',
    km: 6.5,
    tier: 'bronze',
    testedOn: '10 พ.ค. 2569',
    testedOnEn: '10 May 2026',
    clinic: 'รพ.ธนบุรี บำรุงเมือง',
    clinicEn: 'Thonburi Bamrungmuang',
    panel: 'Basic 3-in-1 (HIV / ซิฟิลิส / HBsAg)',
    panelEn: 'Basic 3-in-1 (HIV / Syphilis / HBsAg)',
    bio: 'สายอาร์ต เสพงานดีไซน์เป็นอาหาร เพิ่งไปตรวจพื้นฐานมาปลดล็อก badge',
    bioEn: 'Design is how I spend my weekends. Just did a basic screen to get my badge.',
    tags: ['แกลเลอรี', 'หนัง', 'ดีไซน์', 'แผ่นเสียง'],
    tagsEn: ['Galleries', 'Film', 'Design', 'Vinyl'],
    accent: '#D97706',
  },
  {
    id: 'p6',
    name: 'แจน',
    nameEn: 'Jan',
    age: 24,
    job: 'Fashion Stylist',
    jobEn: 'Fashion stylist',
    area: 'สยาม, กรุงเทพฯ',
    areaEn: 'Siam, Bangkok',
    km: 7.0,
    tier: 'unverified',
    testedOn: null,
    testedOnEn: null,
    clinic: null,
    clinicEn: null,
    panel: null,
    panelEn: null,
    bio: 'ผู้ใช้ใหม่ กำลังดูแพ็กเกจตรวจในแอปอยู่ ชอบคุยเรื่องแฟชั่นกับของกิน',
    bioEn: 'New here, still reading through the screening packages. Fashion and food talk welcome.',
    tags: ['แฟชั่น', 'ของกิน', 'เที่ยว', 'ป็อปคัลเจอร์'],
    tagsEn: ['Fashion', 'Food', 'Travel', 'Pop culture'],
    accent: '#64748B',
  },
];

export const packages = [
  {
    id: 'pkg_free',
    title: 'ตรวจ HIV แบบไม่ระบุตัวตน',
    titleEn: 'Anonymous HIV screening',
    unlocks: 'bronze',
    price: 0,
    wholesale: 0,
    fee: 0,
    turnaround: 'รู้ผลใน 1 ชั่วโมง',
    turnaroundEn: 'Result in 1 hour',
    tests: ['HIV Rapid Test', 'ให้คำปรึกษาก่อน–หลังตรวจ'],
    testsEn: ['HIV rapid test', 'Pre- and post-test counselling'],
    guidance: 'คนไทยทุกคนมีสิทธิ์ตรวจ HIV ฟรีปีละ 2 ครั้งภายใต้ สปสช.',
    guidanceEn: 'Every Thai citizen can screen for HIV free twice a year under NHSO.',
  },
  {
    id: 'pkg_bronze',
    title: 'Basic STI Screening',
    titleEn: 'Basic STI screening',
    unlocks: 'bronze',
    price: 1490,
    wholesale: 1190,
    fee: 300,
    turnaround: 'ทราบผลใน 2–4 ชั่วโมง (Rapid Test)',
    turnaroundEn: 'Result in 2–4 hours (rapid test)',
    tests: ['HIV 4th Gen Ag/Ab Combo', 'Syphilis RPR / TPHA', 'Hepatitis B Surface Antigen (HBsAg)'],
    testsEn: ['HIV 4th-gen Ag/Ab combo', 'Syphilis RPR / TPHA', 'Hepatitis B surface antigen (HBsAg)'],
    guidance: 'ตรวจคัดกรองพื้นฐาน ครอบคลุมเชื้อที่พบบ่อยที่สุดสามตัว',
    guidanceEn: 'A first screening covering the three most common infections.',
  },
  {
    id: 'pkg_silver',
    title: 'Comprehensive 14 STIs Panel',
    titleEn: 'Comprehensive 14-STI panel',
    unlocks: 'silver',
    price: 2990,
    wholesale: 2400,
    fee: 590,
    turnaround: 'ทราบผลใน 24–48 ชั่วโมง',
    turnaroundEn: 'Result in 24–48 hours',
    tests: [
      'HIV 4th Gen Ag/Ab Combo',
      'Syphilis RPR และ Treponema-specific',
      'Hepatitis B และ C Antibodies',
      'Chlamydia trachomatis (Urine PCR)',
      'Neisseria gonorrhoeae (Urine PCR)',
      'Trichomonas vaginalis PCR',
      'Mycoplasma genitalium / hominis PCR',
    ],
    testsEn: [
      'HIV 4th-gen Ag/Ab combo',
      'Syphilis RPR and treponema-specific',
      'Hepatitis B and C antibodies',
      'Chlamydia trachomatis (urine PCR)',
      'Neisseria gonorrhoeae (urine PCR)',
      'Trichomonas vaginalis PCR',
      'Mycoplasma genitalium / hominis PCR',
    ],
    guidance: 'รอบการตรวจ 3–6 เดือนตามที่ CDC แนะนำสำหรับผู้ที่มีเพศสัมพันธ์สม่ำเสมอ',
    guidanceEn: 'The 3–6 month cadence the CDC recommends for sexually active adults.',
  },
  {
    id: 'pkg_gold',
    title: 'Ultra Multiplex DNA 28 + วัคซีน HPV',
    titleEn: 'Ultra Multiplex DNA 28 + HPV vaccine',
    unlocks: 'platinum',
    price: 5900,
    wholesale: 4800,
    fee: 1100,
    turnaround: 'ทราบผลใน 48 ชั่วโมง',
    turnaroundEn: 'Result in 48 hours',
    tests: [
      'Multiplex DNA PCR 28 เชื้อในระบบทางเดินปัสสาวะและสืบพันธุ์',
      'Ureaplasma urealyticum และ parvum DNA',
      'HSV 1 และ 2 DNA PCR',
      'วัคซีน Gardasil 9 (1 เข็ม)',
      'ปรึกษาแพทย์เฉพาะทางโรคติดเชื้อผ่าน Telehealth 1 ครั้ง',
    ],
    testsEn: [
      '28-target urogenital Multiplex DNA PCR',
      'Ureaplasma urealyticum and parvum DNA',
      'HSV 1 and 2 DNA PCR',
      'Gardasil 9 vaccine (one dose)',
      'One telehealth consult with an ID specialist',
    ],
    guidance: 'ครอบคลุมที่สุดในแอป ได้ Badge Platinum เมื่อฉีดวัคซีนครบโดส',
    guidanceEn: 'The most complete panel here. Platinum is awarded once the vaccine course is finished.',
  },
];

export const hospitals = [
  {
    id: 'hosp_bdms',
    name: 'BDMS Wellness และ รพ.กรุงเทพ',
    nameEn: 'BDMS Wellness and Bangkok Hospital',
    group: 'Bangkok Dusit Medical Services',
    branches: 'ซอยศูนย์วิจัย, สยามพารากอน, ชิดลม',
    branchesEn: 'Soi Soonvijai, Siam Paragon, Chidlom',
    fhir: 'https://fhir.bdms.co.th/r4/Observation',
    rating: 4.9,
    zkvActive: true,
  },
  {
    id: 'hosp_bh',
    name: 'รพ.บำรุงราษฎร์ อินเตอร์เนชั่นแนล',
    nameEn: 'Bumrungrad International',
    group: 'Bumrungrad Health Network',
    branches: 'สุขุมวิท ซอย 3',
    branchesEn: 'Sukhumvit Soi 3',
    fhir: 'https://api.bumrungrad.com/fhir/DiagnosticReport',
    rating: 4.9,
    zkvActive: true,
  },
  {
    id: 'hosp_pulse',
    name: 'Pulse Clinic Bangkok',
    nameEn: 'Pulse Clinic Bangkok',
    group: 'Pulse Healthcare Asia',
    branches: 'สีลม, สยาม, อโศก, พญาไท',
    branchesEn: 'Silom, Siam, Asok, Phaya Thai',
    fhir: 'https://api.pulse-clinic.com/fhir/v1/ZkvCheck',
    rating: 4.8,
    zkvActive: true,
  },
  {
    id: 'hosp_thonburi',
    name: 'รพ.ธนบุรี บำรุงเมือง',
    nameEn: 'Thonburi Bamrungmuang',
    group: 'Thonburi Healthcare Group',
    branches: 'ถนนบำรุงเมือง',
    branchesEn: 'Bamrungmuang Road',
    fhir: 'https://fhir.thonburi.com/his/zkv',
    rating: 4.7,
    zkvActive: true,
  },
];

export const initialConversations = [
  {
    id: 'conv_p1',
    partnerId: 'p1',
    matchedOn: 'เมื่อวานนี้',
    matchedOnEn: 'Yesterday',
    unread: 1,
    messages: [
      {
        id: 'm0',
        system: true,
        text: 'คุณและหมอแพรวต่างผ่านการยืนยันผลตรวจระดับ Platinum จาก รพ.บำรุงราษฎร์ และ BDMS Wellness',
        textEn: 'You and Praew are both verified at Platinum by Bumrungrad and BDMS Wellness.',
        time: '10:30',
      },
      {
        id: 'm1',
        mine: false,
        text: 'สวัสดีค่ะ ดีใจที่ได้แมตช์นะคะ หายากมากที่จะเจอคนที่ตรวจครบแพ็กเกจเหมือนกัน',
        textEn: "Hi! Glad we matched. It's rare to find someone who does the full panel too.",
        time: '10:32',
      },
      {
        id: 'm2',
        mine: true,
        text: 'สวัสดีครับ เห็นในโปรไฟล์บอกว่าชอบวิ่งมาราธอน ปกติซ้อมที่ไหนครับ',
        textEn: 'Hi! Your profile says marathons. Where do you usually train?',
        time: '10:35',
      },
      {
        id: 'm3',
        mine: false,
        text: 'ที่สวนเบญจกิติช่วงเย็นค่ะ ถ้าว่างสุดสัปดาห์ชวนไปวิ่งหรือจิบกาแฟได้นะคะ',
        textEn: 'Benjakitti Park in the evenings. If you are free this weekend, come run or grab coffee.',
        time: '10:38',
      },
    ],
  },
  {
    id: 'conv_p3',
    partnerId: 'p3',
    matchedOn: '2 วันที่แล้ว',
    matchedOnEn: '2 days ago',
    unread: 0,
    messages: [
      {
        id: 'm4',
        system: true,
        text: 'คุณและมายด์ได้รับการยืนยันผลตรวจจาก Pulse Clinic Siam ระดับ Silver',
        textEn: 'You and Mind are both verified at Silver by Pulse Clinic Siam.',
        time: '14:10',
      },
      {
        id: 'm5',
        mine: false,
        text: 'สวัสดีค่า ชอบรูปกล้องฟิล์มในโปรไฟล์มากเลย โทนสีสวยมาก',
        textEn: 'Hey! Love the film photos on your profile, the colours are lovely.',
        time: '14:15',
      },
      {
        id: 'm6',
        mine: true,
        text: 'ขอบคุณครับ แถวอารีย์มีคาเฟ่แสงสวยเยอะเลย ไว้นัดไปถ่ายกันครับ',
        textEn: 'Thank you! Ari has great light. We should go shoot sometime.',
        time: '14:20',
      },
    ],
  },
];

export const me = {
  name: 'ภณ',
  nameEn: 'Pon',
  age: 28,
  job: 'AI Engineer',
  jobEn: 'AI engineer',
  tier: 'silver',
  testedOn: '28 ก.ค. 2569',
  testedOnEn: '28 Jul 2026',
  clinic: 'BDMS Wellness Clinic',
  clinicEn: 'BDMS Wellness Clinic',
  daysLeft: 142,
};
